### ISSUE TITLE
InpAxisEvt_Turn_K2Node_InputAxisEvent_157

### ISSUE THREAD

**Issue by huiger8723** [IriskaDev/slua_unreal_demo#1]
这种函数名是怎么生成的，后面的数字157哪儿来的

**Comment by IriskaDev** [comment]
这个是UE4的内部事件，如果Actor的派生类有实现ProcessEvent这样的函数的话，自定的输入事件被触发的时候，事件会在这个函数内处理，可以通过func->GetName()取到具体的函数名，实例可以参考LuaActor.h的实现。

**Comment by git-mingfei** [comment]
让我摸索了了好几天，蓝图拖出该节点，然后复制，把粘贴板里的内容复制到文本里，里面有个CustomFunctionName 字段，就是这个名字
