### ISSUE TITLE
无法获取函数中的默认值

### ISSUE THREAD

**Issue by l747369** [IriskaDev/slua_unreal_demo#2]
比如AHUD里面有函数：
void DrawTextureSimple(UTexture* Texture, float ScreenX, float ScreenY, float Scale=1.f, bool bScalePosition=false);

Lua函数中，
self:DrawTextureSimple(self["CrossTexture"], halfX, halfY)
这样写会执行失败；
必须把原本可以缺省的变量补全才可以运行。

**Comment by IriskaDev** [comment]
sluaunreal中确实是会有这个问题
这个问题可以到sluaunreal项目下提issue，看看大神是否有解决方案，以下是项目地址
https://github.com/Tencent/sluaunreal
