### ISSUE TITLE
加载地图失败！ ../../../../slua_unreal_demo/Content/FirstPersonBP/Maps/FirstPersonExampleMap.umap是一张虚幻引擎4地图[File:v517]，来自一个比这个[Cur:v514]更新的引擎版本。

### ISSUE THREAD

**Issue by pilaoda** [IriskaDev/slua_unreal_demo#3]
使用的是github上ue4的4.18分支，用vs2015编译，第一次打开就出现这种情况。
加载地图失败！
../../../../slua_unreal_demo/Content/FirstPersonBP/Maps/FirstPersonExampleMap.umap是一张虚幻引擎4地图[File:v517]，来自一个比这个[Cur:v514]更新的引擎版本。

**Comment by IriskaDev** [comment]
工程是使用4.21的引擎开发的，你需要使用4.21及以上版本的引擎才能正常运行此工程

**Comment by pilaoda** [comment]
> 工程是使用4.21的引擎开发的，你需要使用4.21及以上版本的引擎才能正常运行此工程

非常感谢解答，如果可以把引擎版本信息加到readme里面那就更棒了~

**Comment by IriskaDev** [comment]
好的，这边会把引擎版本加上
