### ISSUE TITLE
UE4.25无法运行demo

### ISSUE THREAD

**Issue by ohday** [IriskaDev/slua_unreal_demo#5]
Hi，UE4.25无法跑通该demo。从slua官方仓库拷贝了4.25的branch之后，运行时会挂在这里：
![image](https://user-images.githubusercontent.com/5044367/84266371-f427af00-ab56-11ea-8377-ac08fed395ae.png)

**Comment by IriskaDev** [comment]
收到，这周末我看一看

**Comment by IriskaDev** [comment]
问题已修复，切换至 branch_ue_4_25 分支即可
