### ISSUE TITLE
请问 lua  里的输入事件是怎么绑定的？

### ISSUE THREAD

**Issue by git-mingfei** [IriskaDev/slua_unreal_demo#6]
MyCharacter.lua 里的   InpAxisEvt_MoveForward_K2Node_InputAxisEvent_181  事件是如何绑定的？

**Comment by git-mingfei** [comment]
让我摸索了了好几天，蓝图拖出该节点，然后复制，把粘贴板里的内容复制到文本里，里面有个CustomFunctionName 字段，就是这个名字

**Comment by IriskaDev** [comment]
不好意思没注意看邮件
细节我记不太清楚了，大概是用下面的方式获取的名字
断点LuaActor中的 ProcessEvent 函数，Input事件触发时该函数会被调用，此时会传进来一个UFunction的指针，func->GetName()即是该事件的事件名

**Comment by IriskaDev** [comment]
或者也可以直接断点LuaBase::luaImplemented函数
